package roman.com.javaquizapp;

import android.databinding.DataBindingUtil;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;

import roman.com.javaquizapp.databinding.ActivityMainBinding;

public class MainActivity extends AppCompatActivity {

    //autogenerated class by the databinding library
    private ActivityMainBinding mBinding;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        //get the binding object for activity_main.xml
        mBinding = DataBindingUtil.setContentView(this, R.layout.activity_main);
    }
}
